using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Windows.Forms;
using AGApp.Proc;
using AGApp.Dialog;

namespace AGApp.Control.Parts
{
    public partial class SettingControl : UserControl
    {
        #region [ アクセサ ]

        /// <summary>
        /// 設定処理デリゲート
        /// </summary>
        public SettingProc _SettingProc { set; get; }

        /// <summary>
        /// 再接続処理デリゲート
        /// </summary>
        public ReconnectProc _ReconnectProc { set; get; }

        #endregion

        /// <summary>
        /// コンストラクタ
        /// </summary>
        public SettingControl()
        {
            InitializeComponent();

#if !DEBUG
            // 番組表生成
            this.button1.Visible = false;
#endif
        }

        /// <summary>
        /// バージョン確認ボタン
        /// </summary>
        /// <param name="sender">オブジェクト</param>
        /// <param name="e">イベント</param>
        private void versionChkBtn_Click(object sender, EventArgs e)
        {
            using (VersionDialog dialog = new VersionDialog())
            {
                dialog.StartPosition = FormStartPosition.CenterParent;
                dialog.ShowDialog();
//                dialog.DialogClosed();
            }
        }

        /// <summary>
        /// 最新バージョン取得
        /// </summary>
        /// <param name="sender">オブジェクト</param>
        /// <param name="e">イベント</param>
        private void versionBtn_Click(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start("http://www.vector.co.jp/soft/winnt/net/se495261.html");
        }

        /// <summary>
        /// ヘルプボタン押下時イベント
        /// </summary>
        /// <param name="sender">オブジェクト</param>
        /// <param name="e">イベント</param>
        private void helpButton_Click(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start(@"http://okya.webcrow.jp/agapp/");
        }


        /// <summary>
        /// 再接続ボタン
        /// </summary>
        /// <param name="sender">オブジェクト</param>
        /// <param name="e">イベント</param>
        private void retryBtn_Click(object sender, EventArgs e)
        {
            this._ReconnectProc();
        }

        /// <summary>
        /// 番組表表示
        /// </summary>
        /// <param name="sender">オブジェクト</param>
        /// <param name="e">イベント</param>
        private void timetableViewBtn_Click(object sender, EventArgs e)
        {
            //TimeTableDialog dialog = new TimeTableDialog();
            //dialog.Show();
        }

        /// <summary>
        /// 番組データ作成
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void button1_Click(object sender, EventArgs e)
        {
            // 番組表作成
            List<AGData> lstAgData = new List<AGData>();
            // 月曜日
            AGData agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "6:00";
            agData._Repeat = true;
            agData._Name = "ツブ☆ドル　ユメカナラジオ！？（杉田菜摘・豊田萌絵・優木かな）";
            agData._Mail = "tubu@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "6:30";
            agData._Repeat = true;
            agData._Name = "木戸衣吹・エリイちゃんの　ゆめいろ学院";
            agData._Mail = "yumedoki@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "三上詩織のA&G NEXT GENERATION Lady Go!!";
            agData._Mail = "shiori.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "8:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（富沢恵莉）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._HashTag = "#alb5";
            agData._Mail = "alb5@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "8:30";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Blog = @"";
            agData._Name = "高橋美佳子のマルごとぴ～なっつ！";
            agData._Mail = "marup@joqr.net";
            lstAgData.Add(agData);
            /*
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "9:00";
            agData._Repeat = true;
            agData._Name = "RADIO RONDO ROBE（川田まみ・Ray）";
            agData._Mail = "rrr@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "9:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "Radio 4 Gamer TAP(仮）（マフィア梶田・マンスリーアシスタント）";
            agData._Mail = "4gamer@joqr.net";
            lstAgData.Add(agData);
            */
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "10:30";
            agData._Repeat = true;
            agData._Name = "EMERGENCY the RADIO（NEW YOUNG・CRAZY YU・DANCING YUKARI）";
            agData._Mail = "emergency@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "11:00";
            agData._Repeat = true;
            agData._Name = "小野大輔・近藤孝行の夢冒険～Dragon&Tiger";
            agData._Blog = "http://www.joqr.co.jp/blog/ddt/";
            agData._Mail = "ddt@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/zeni/";
            agData._Name = "有限会社チェリーベル（櫻井孝宏・鈴村健一・松来未祐）";
            agData._Mail = "zeni@joqr.net";
            agData._HashTag = "#cherrybell";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "12:00";
            agData._Repeat = true;
            agData._Name = "羽多野・寺島 Radio 2D LOVE（羽多野渉・寺島拓篤）";
            agData._Blog = "http://www.marine-e.net/sp/2dlove/";
            agData._Mail = "2dlove@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "12:30";
            agData._Repeat = true;
            agData._Name = "吉野裕行FC";
            agData._Blog = "";
            agData._Mail = "yfc@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE THE CATCH（鷲崎健）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "take@joqr.net";
            agData._HashTag = "#catch";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "14:30";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "A&G NEXT BREAKS 吉田有里のFIVE STARS";
            agData._Mail = "yuuri@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "15:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "逢坂市立花江学園～Radio（逢坂良太・花江夏樹）";
            agData._Mail = "ouhana@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "15:30";
            agData._Repeat = true;
            agData._Name = "黒子のバスケ 放送委員会（小野賢章・小野友樹）";
            agData._Mail = "kurobas@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "16:00";
            agData._Movie = true;
            agData._Name = "アニアモ！（川上莉央・立花理香）";
            agData._Blog = "http://www.joqr.co.jp/aniamo/";
            agData._Mail = "aniamo@joqr.net";
            lstAgData.Add(agData);
            /*
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "17:00";
            agData._Movie = true;
            agData._Name = "本気（マジ）！アニラブ（立花芙実）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb1@joqr.net";
            lstAgData.Add(agData);
            */
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "17:30";
            agData._Name = "ミリオンドール～リアルすぎるアイドルラジオ～（楠田亜衣奈・伊藤美来）";
            agData._Mail = "million@obc1314.com";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE THE CATCH（アース・スター・ドリーム）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "19:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（上坂すみれ）";
            agData._Mail = "sumire.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._Time = "19:30";
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Movie = true;
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "19:40";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（メゾン・ド・イーコエ（長妻樹里・Machico））";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "20:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "20:10";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（メゾン・ド・イーコエ（長妻樹里・Machico））";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "21:00";
            agData._Name = "内田さんと浅倉さん（内田彩・朝倉杏美）";
            agData._Mail = "ua@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "21:30";
            agData._Name = "東山奈央のドリーム*シアター";
            agData._Mail = "nao@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "22:00";
            agData._Live = true;
            agData._Movie = true;
            agData._Name = "井口裕香のむ～～～ん⊂（　＾ω＾）⊃";
            agData._Mail = "yukachi@joqr.net";
            agData._HashTag = "#muuuun";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "23:00";
            agData._Movie = true;
            agData._Name = "阿澄佳奈 星空ひなたぼっこ";
            agData._Mail = "asumin@joqr.net";
            agData._HashTag = "#hoshihina";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "0:00";
            agData._Name = "儀武ゆう子\"ＳＵＮ\"";
            agData._Movie = true;
            agData._Blog = "";
            agData._Mail = "sun@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "0:30";
            agData._Name = "能登麻美子 おはなしNOTE";
            agData._Blog = "";
            agData._Mail = "note@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "1:00";
            agData._Name = "ごぶごぶちゃん☆（中村繪里子・田村睦心）";
            agData._Mail = "gobu@joqr.net";
            agData._Blog = "http://seaside-c.jp/program/gobu/";
            agData._HashTag = "#gobugobuchan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "1:30";
            agData._Name = "ありがた系迷惑プレゼンショー　はるか・ちなみの「りめいく！」（佳村はるか・橋本ちなみ）";
            agData._Mail = "remake@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "2:00";
            agData._Movie = true;
            agData._Name = "諏訪道彦のスワラジ";
            agData._Mail = "suwacchi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（上坂すみれ）";
            agData._Mail = "sumire.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Monday;
            agData._Time = "3:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（立花芙実）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb1@joqr.net";
            lstAgData.Add(agData);

            // 火曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "6:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "伊福部崇のラジオのラジオ（伊福部崇・鈴木美咲）";
            agData._Mail = "radioradio@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "6:30";
            agData._Repeat = true;
            agData._Name = "のざP＆松永真穂のLive Dog（野崎圭一・松永真穂）";
            agData._Mail = "dog@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（上坂すみれ）";
            agData._Mail = "sumire.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "8:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（立花芙実）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb1@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "8:30";
            agData._Repeat = true;
            agData._Name = "\"回覧版\"もしも声優がいっぱい住んでいるマンションがあったら（岩田光央・秦佐和子）";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "9:00";
            agData._Name = "内田さんと浅倉さん（内田彩・朝倉杏美）";
            agData._Mail = "ua@joqr.net";
            agData._Repeat = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "9:30";
            agData._Name = "東山奈央のドリーム*シアター";
            agData._Mail = "nao@joqr.net";
            agData._Repeat = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "10:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "井口裕香のむ～～～ん⊂（　＾ω＾）⊃";
            agData._Mail = "yukachi@joqr.net";
            agData._HashTag = "#muuuun";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "11:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "阿澄佳奈 星空ひなたぼっこ";
            agData._Mail = "asumin@joqr.net";
            agData._HashTag = "#hoshihina";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "12:00";
            agData._Name = "儀武ゆう子\"ＳＵＮ\"";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "";
            agData._Mail = "sun@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "12:30";
            agData._Name = "能登麻美子 おはなしNOTE";
            agData._Blog = "";
            agData._Repeat = true;
            agData._Mail = "note@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（メゾン・ド・イーコエ（長妻樹里・Machico））";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._Time = "13:30";
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "13:40";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（メゾン・ド・イーコエ（長妻樹里・Machico））";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "14:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "14:10";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（メゾン・ド・イーコエ（長妻樹里・Machico））";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "ekoe.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "15:00";
            agData._Repeat = true;
            agData._Name = "ごぶごぶちゃん☆（中村繪里子・田村睦心）";
            agData._Mail = "gobu@joqr.net";
            agData._Blog = "http://seaside-c.jp/program/gobu/";
            agData._HashTag = "#gobugobuchan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "15:30";
            agData._Repeat = true;
            agData._Name = "ありがた系迷惑プレゼンショー　はるか・ちなみの「りめいく！」（佳村はるか・橋本ちなみ）";
            agData._Mail = "remake@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "16:00";
            agData._Movie = true;
            agData._Name = "きり～つ！れいっ！姫イド隊";
            agData._Mail = "himeido@joqr.net";
            agData._HashTag = "#himeido";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "16:30";
            agData._Name = "剣と魔法のログレスラジオ（石田晴香・青木瑠璃子）";
            agData._Mail = "log@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "17:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（小松未可子）";
            agData._Mail = "mikako.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Name = "角元明日香の本気（マジ）！アニラブ";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb2@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "18:30";
            agData._Movie = true;
            agData._Name = "砂山・赤崎アワー　えじまる（砂山圭大郎・赤崎千夏）";
            agData._Mail = "agmaru@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "19:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._Movie = true;
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "19:30";
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "19:40";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "20:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "20:10";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "21:00";
            agData._Name = "井上麻里奈・下田麻美のIT革命!";
            agData._Blog = "http://it.dlsite.com/";
            agData._Mail = "it@joqr.net";
            agData._HashTag = "#itkakumei";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "21:30";
            agData._Name = "早見沙織のふり～すたいる♪";
            agData._Mail = "frst@joqr.net";
            agData._HashTag = "#frst";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "22:00";
            agData._Live = true;
            agData._Movie = true;
            agData._Name = "高橋美佳子の の～ぷらんでいこう♪";
            agData._Mail = "no@joqr.net";
            agData._HashTag = "#no_plan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "23:00";
            agData._Name = "竹達・沼倉の初ラジ！（竹達彩奈・沼倉愛美）";
            agData._Mail = "wiwi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "23:30";
            agData._Movie = true;
            agData._Name = "岡本信彦のアナログゲームを教えてあげる☆";
            agData._Mail = "age2@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Movie = true;
            agData._Time = "0:00";
            agData._Name = "久保ユリカが１人しゃべりなんて胃が痛い。";
            agData._Mail = "shikaco@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "0:30";
            agData._Name = "TrySailのTRYangle harmony（麻倉もも・雨宮天・夏川椎菜）";
            agData._Blog = "";
            agData._Mail = "try@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "1:00";
            agData._Name = "洲崎西（洲崎綾・西明日香）";
            agData._Blog = "http://seaside-c.jp/program/suzakinishi/";
            agData._Mail = "suzakinishi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "1:30";
            agData._Name = "中村繪里子の「ら・ら・ら なかむランド～Love・Laugh・Life」";
            agData._Mail = "nakamuland@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "2:00";
            agData._Name = "X RADIOS（bamboo(milktub)・上田朱音）";
            agData._Mail = "dmm@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（小松未可子）";
            agData._Mail = "mikako.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Tuesday;
            agData._Time = "3:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（角元明日香）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb2@joqr.net";
            lstAgData.Add(agData);

            // 水曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "6:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "きり～つ！れいっ！姫イド隊";
            agData._Mail = "himeido@joqr.net";
            agData._HashTag = "#himeido";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "6:30";
            agData._Repeat = true;
            agData._Name = "X RADIOS（bamboo(milktub)・上田朱音）";
            agData._Mail = "dmm@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（小松未可子）";
            agData._Mail = "mikako.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "8:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（角元明日香）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb2@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "8:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "砂山・赤崎アワー　えじまる（砂山圭大郎・赤崎千夏）";
            agData._Mail = "agmaru@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Repeat = true;
            agData._Time = "9:00";
            agData._Name = "井上麻里奈・下田麻美のIT革命!";
            agData._Blog = "http://it.dlsite.com/";
            agData._Mail = "it@joqr.net";
            agData._HashTag = "#itkakumei";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "9:30";
            agData._Repeat = true;
            agData._Name = "早見沙織のふり～すたいる♪";
            agData._Mail = "frst@joqr.net";
            agData._HashTag = "#frst";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "10:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "高橋美佳子の の～ぷらんでいこう♪";
            agData._Mail = "no@joqr.net";
            agData._HashTag = "#no_plan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "11:00";
            agData._Repeat = true;
            agData._Name = "竹達・沼倉の初ラジ！（竹達彩奈・沼倉愛美）";
            agData._Mail = "wiwi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "岡本信彦のアナログゲームを教えてあげる☆";
            agData._Mail = "age2@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "12:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "久保ユリカが１人しゃべりなんて胃が痛い。";
            agData._Mail = "shikaco@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Repeat = true;
            agData._Time = "12:30";
            agData._Name = "TrySailのTRYangle harmony（麻倉もも・雨宮天・夏川椎菜）";
            agData._Blog = "";
            agData._Mail = "try@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "13:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "13:40";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "14:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "14:10";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（Gero）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "gero.2h@joqr.net";
            agData._HashTag = "#2h";
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "15:00";
            agData._Name = "洲崎西（洲崎綾・西明日香）";
            agData._Repeat = true;
            agData._Blog = "http://seaside-c.jp/program/suzakinishi/";
            agData._Mail = "suzakinishi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "15:30";
            agData._Repeat = true;
            agData._Name = "中村繪里子の「ら・ら・ら なかむランド～Love・Laugh・Life」";
            agData._Mail = "nakamuland@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "16:00";
            agData._Name = "アクターズゲート　未佐子と宗司のフレッシュ☆ドリームキャンパス（関口未佐子・津田宗司）";
            agData._Mail = "gate@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "16:30";
            agData._Movie = true;
            agData._Name = "兼斗・健太郎の漢気Radio（白石兼斗・森岡健太郎）";
            agData._Mail = "otokogi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "17:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（大久保瑠美）";
            agData._Mail = "rumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Name = "本気（マジ）！アニラブ（藤原未来）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb3@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "18:30";
            agData._Name = "楠田亜衣奈・渡部優衣の気分上等↑↑";
            agData._Mail = "ageage@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "19:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "19:30";
            agData._Movie = true;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "19:40";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "20:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "20:10";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "21:00";
            agData._Name = "花澤香菜のひとりでできるかな?";
            agData._Blog = "http://www.joqr.co.jp/blog/hanazawa/";
            agData._Mail = "dekirukana@joqr.net";
            agData._HashTag = "#hitokana";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "22:00";
            agData._Live = true;
            agData._Name = "超!mobile A&G presents 生放送!〔月3回更新〕（諏訪部順一 with ゲスト、マンスリーパーソナリティ(月替) ）";
            agData._Mail = "nama@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "23:00";
            agData._Movie = true;
            agData._Name = "矢作・佐倉のちょっとお時間よろしいですか（矢作紗友里・佐倉綾音）";
            agData._Blog = "";
            agData._Mail = "ojikan@joqr.net";
            agData._HashTag = "#ojikan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "23:30";
            agData._Name = "あおい・さおりの新番組 ( ｀・ш・´ )（悠木碧・早見沙織）";
            agData._Mail = "doya@joqr.net";
            agData._HashTag = "#aoisaori";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "0:00";
            agData._Live = true;
            agData._Movie = true;
            agData._Name = "ヒャダインのわーきゃーいわれたい";
            agData._Mail = "wa@joqr.net";
            agData._HashTag = "#wakya";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "1:00";
            agData._Name = "津田のラジオ「っだー！！」（津田美波）";
            agData._Mail = "daaaaa@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "1:30";
            agData._Name = "由佳・ありさ・未奈美のＭラジ！！（大坪由佳・清都ありさ・高橋未奈美）";
            agData._Mail = "mmm@joqr.net"; 
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "2:00";
            agData._Name = "今村彩夏 STAY GOLD";
            agData._Mail = "ayaka@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（大久保瑠美）";
            agData._Mail = "rumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Wednesday;
            agData._Time = "3:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（藤原未来）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb3@joqr.net";
            lstAgData.Add(agData);

            // 木曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "6:00";
            agData._Repeat = true;
            agData._Name = "アクターズゲート　未佐子と宗司のフレッシュ☆ドリームキャンパス（関口未佐子・津田宗司）";
            agData._Mail = "gate@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "6:30";
            agData._Repeat = true;
            agData._Name = "今村彩夏 STAY GOLD";
            agData._Mail = "ayaka@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（大久保瑠美）";
            agData._Mail = "rumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "8:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（藤原未来）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb3@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "8:30";
            agData._Repeat = true;
            agData._Name = "楠田亜衣奈・渡部優衣の気分上等↑↑";
            agData._Mail = "ageage@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "9:00";
            agData._Repeat = true;
            agData._Name = "花澤香菜のひとりでできるかな?";
            agData._Blog = "http://www.joqr.co.jp/blog/hanazawa/";
            agData._Mail = "dekirukana@joqr.net";
            agData._HashTag = "#hitokana";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "10:00";
            agData._Movie = true;
            agData._Name = "超!mobile A&G presents 生放送!〔月3回更新〕（諏訪部順一 with ゲスト、マンスリーパーソナリティ(月替) ）";
            agData._Mail = "nama@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "11:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "矢作・佐倉のちょっとお時間よろしいですか（矢作紗友里・佐倉綾音）";
            agData._Blog = "";
            agData._Mail = "ojikan@joqr.net";
            agData._HashTag = "#ojikan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Name = "あおい・さおりの新番組 ( ｀・ш・´ )（悠木碧・早見沙織 ）";
            agData._Mail = "doya@joqr.net";
            agData._HashTag = "#aoisaori";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "12:00";
            agData._Repeat = true;
            agData._Name = "津田のラジオ「っだー！！」（津田美波）";
            agData._Mail = "daaaaa@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "12:30";
            agData._Repeat = true;
            agData._Name = "由佳・ありさ・未奈美のＭラジ！！（大坪由佳・清都ありさ・高橋未奈美）";
            agData._Mail = "mmm@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "13:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "13:40";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "14:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "14:10";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（佐土原かおり）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "kaori.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "15:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "ヒャダインのわーきゃーいわれたい";
            agData._Mail = "wa@joqr.net";
            agData._HashTag = "#wakya";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "16:00";
            agData._Name = "野水いおりの厨二病をこじらせたワタシが,アンタたちも道連れにしてやるラジオ";
            agData._Mail = "";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "16:30";
            agData._Name = "新人声優読本（湊ちひろ・田中聖奈・長門石まお）";
            agData._Mail = "deview@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "17:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（高森奈津美）";
            agData._Mail = "natsumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Name = "本気（マジ）！アニラブ（七瀬亜深）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb4@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "18:30";
            agData._Name = "ノン子とのび太のアニメスクランブル（日高のり子・長谷川のび太）";
            agData._Blog = "http://www.joqr.net/blog/anisc/";
            agData._Mail = "anisc@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "19:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "19:30";
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Movie = true;
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "19:40";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "20:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "20:10";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "21:00";
            agData._Name = "杉田智和のアニゲラディドゥーーン";
            agData._Mail = "gera@joqr.net";
            agData._HashTag = "#anigera";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "22:00";
            agData._Movie = true;
            agData._Name = "花江夏樹のボイス執事～お嬢様、お時間です～";
            agData._Blog = "";
            agData._Mail = "shitsuji@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "22:30";
            agData._Live = true;
            agData._Name = "豊崎愛生のおかえりらじお";
            agData._Mail = "okaeri@joqr.net";
            agData._HashTag = "#okaeri";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "23:30";
            agData._Name = "高垣彩陽のあしたも晴レルヤ";
            agData._Mail = "ayahi@joqr.net";
            agData._HashTag = "#hareruya";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "0:00";  
            agData._Name = "矢作紗友里・東山奈央のRADIO・XBLAZE";
            agData._Mail = "rxb@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "0:30";
            agData._Movie = true;
            agData._Name = "加藤英美里・田中美海のとら娘れでぃお！";
            agData._Mail = "tora@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "1:00";
            agData._Name = "金田朋子・保村真のエアラジオ";
            agData._Blog = "http://www.joqr.co.jp/blog/air-radio/";
            agData._Mail = "air@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "1:30";
            agData._Name = "水島大宙・木村良平　←ＳＩＤＥ ＢＹ ＳＩＤＥ→";
            agData._Mail = "side@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "2:00";
            agData._Movie = true;
            agData._Name = "瑠璃子・葵のＡＯ進化論（青木瑠璃子・葵）";
            agData._Mail = "blue@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（高森奈津美）";
            agData._Mail = "natsumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "3:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（七瀬亜深）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb4@joqr.net";
            lstAgData.Add(agData);

            // ここから修正   2014.11.10
            // 金曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "6:00";
            agData._Repeat = true;
            agData._Name = "ソードアート・オンエアー2（鷲崎健・松岡禎丞・戸松遥）";
            agData._Mail = "sao@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "6:30";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "瑠璃子・葵のＡＯ進化論（青木瑠璃子・葵）";
            agData._Mail = "blue@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（高森奈津美）";
            agData._Mail = "natsumi.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "8:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（七瀬亜深）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb4@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "8:30";
            agData._Repeat = true;
            agData._Name = "ノン子とのび太のアニメスクランブル（日高のり子・長谷川のび太）";
            agData._Blog = "http://www.joqr.net/blog/anisc/";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "9:00";
            agData._Repeat = true;
            agData._Name = "豊崎愛生のおかえりらじお";
            agData._Mail = "okaeri@joqr.net";
            agData._HashTag = "#okaeri";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "10:00";
            agData._Repeat = true;
            agData._Name = "杉田智和のアニゲラディドゥーーン";
            agData._Mail = "gera@joqr.net";
            agData._HashTag = "#anigera";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "11:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "花江夏樹のボイス執事～お嬢様、お時間です～";
            agData._Blog = "";
            agData._Mail = "shitsuji@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Name = "高垣彩陽のあしたも晴レルヤ";
            agData._Mail = "ayahi@joqr.net";
            agData._HashTag = "#hareruya";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "12:00";
            agData._Name = "矢作紗友里・東山奈央のRADIO・XBLAZE";
            agData._Mail = "rxb@joqr.net";
            agData._Repeat = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "12:30";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "加藤英美里・田中美海のとら娘れでぃお！";
            agData._Mail = "tora@joqr.net";
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "13:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "13:40";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "14:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "14:10";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "A&G ARTIST ZONE 2h（AiRi）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "airi.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "15:00";
            agData._Repeat = true;
            agData._Name = "金田朋子・保村真のエアラジオ";
            agData._Blog = "http://www.joqr.co.jp/blog/air-radio/";
            agData._Mail = "air@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "15:30";
            agData._Repeat = true;
            agData._Name = "水島大宙・木村良平　←ＳＩＤＥ ＢＹ ＳＩＤＥ→";
            agData._Mail = "side@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "16:00";
            agData._Name = "超！A＆Gスペシャル";
            agData._Mail = "sag@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "17:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（三上詩織）";
            agData._Mail = "shiori.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Name = "本気（マジ）！アニラブ（富沢恵莉）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb5@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "18:30";
            agData._Movie = true;
            agData._Blog = @"http://enomoto-office.com/radio/kakitakunaru.html";
            agData._Name = "榎本事務所presents 大久保瑠美のラノベが書きたくなるラジオ（大久保瑠美・芦澤佳純）";
            agData._Mail = "kakitakunaru@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "19:00";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（鷲崎健）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "take.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "19:30";
            agData._Name = "織田かおりのもっとColorful Mode";
            agData._Movie = true;
            agData._Mail = "kaori@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "19:40";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（鷲崎健）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "take.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "20:00";
            agData._Movie = true;
            agData._Name = "三澤紗千香のreal oneself";
            agData._Mail = "sachika@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "20:10";
            agData._Movie = true;
            agData._Live = true;
            agData._Name = "A&G ARTIST ZONE 2h（鷲崎健）";
            agData._Blog = "http://www.joqr.co.jp/blog/2h/";
            agData._Mail = "take.2h@joqr.net";
            agData._HashTag = "#2h";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "21:00";
            agData._Name = "RADIO RONDO ROBE（川田まみ・Ray）";
            agData._Mail = "rrr@joqr.net";
            agData._HashTag = "#rrr";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Movie = true;
            agData._Time = "21:30";
            agData._Name = "Radio 4 Gamer TAP(仮）（マフィア梶田・マンスリーアシスタント）";
            agData._Mail = "4gamer@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "22:30";
            agData._Name = "EMERGENCY the RADIO（NEW YOUNG・CRAZY YU・DANCING YUKARI）";
            agData._Mail = "emergency@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "23:00";
            agData._Name = "小野大輔・近藤孝行の夢冒険～Dragon&Tiger";
            agData._Blog = "http://www.joqr.co.jp/blog/ddt/";
            agData._Mail = "ddt@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "23:30";
            agData._Blog = "http://www.joqr.co.jp/blog/zeni/";
            agData._Name = "有限会社チェリーベル（櫻井孝宏・鈴村健一・松来未祐）";
            agData._Mail = "zeni@joqr.net";
            agData._HashTag = "#cherrybell";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "0:00";
            agData._Name = "羽多野・寺島 Radio 2D LOVE（羽多野渉・寺島拓篤）";
            agData._Blog = "http://www.marine-e.net/sp/2dlove/";
            agData._Mail = "2dlove@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "0:30";
            agData._Name = "吉野裕行FC";
            agData._Blog = "";
            agData._Mail = "yfc@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "1:00";
            agData._Movie = true;
            agData._Name = "逢坂市立花江学園～Radio（逢坂良太・花江夏樹）";
            agData._Mail = "ouhana@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "1:30";
            agData._Name = "黒子のバスケ 放送委員会（小野賢章・小野友樹）";
            agData._Mail = "kurobas@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "2:00";
            agData._Name = "木戸衣吹・エリイちゃんの「ゆめいろ学院 Doki☆Doki参観日」";
            agData._Mail = "yumedoki@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "3:00";
            agData._Movie = true;
            agData._Name = "カスタマイＺのハジメマシタ";
            agData._Mail = "miz@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/lady/";
            agData._Name = "A&G NEXT GENERATION Lady Go!!（三上詩織）";
            agData._Mail = "shiori.lady@joqr.net";
            agData._HashTag = "#ladygo";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Friday;
            agData._Time = "3:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "本気（マジ）！アニラブ（富沢恵莉）";
            agData._Blog = "http://www.joqr.co.jp/alb/";
            agData._Mail = "alb5@joqr.net";
            lstAgData.Add(agData);

            // 土曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "6:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "超!mobile A&G presents 生放送!〔月3回更新〕（諏訪部順一 with ゲスト、マンスリーパーソナリティ(月替) ）";
            agData._Mail = "nama@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "7:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "アニアモ！（川上莉央・立花理香）";
            agData._Blog = "http://www.joqr.co.jp/aniamo/";
            agData._Mail = "aniamo@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "8:00";
            agData._Repeat = true;
            agData._Name = "超！A&Gスペシャル";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "9:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "瑠璃子・葵のＡＯ進化論（青木瑠璃子・葵）";
            agData._Mail = "blue@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "9:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "アフィリア・サーガの魔法学院放送部";
            agData._Mail = "afilia@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "10:00";
            agData._Repeat = true;
            agData._Name = " P.S. 元気です。孝宏（櫻井孝宏）";
            agData._Mail = "psgenki@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "10:30";
            agData._Repeat = true;
            agData._Name = "小野大輔・近藤孝行の夢冒険～Dragon&Tiger";
            agData._Blog = "http://www.joqr.co.jp/blog/ddt/";
            agData._Mail = "ddt@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "11:00";
            agData._Repeat = true;
            agData._Name = "羽多野・寺島 Radio 2D LOVE（羽多野渉・寺島拓篤）";
            agData._Blog = "http://www.marine-e.net/sp/2dlove/";
            agData._Mail = "2dlove@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Blog = "http://www.joqr.co.jp/blog/zeni/";
            agData._Name = "有限会社チェリーベル（櫻井孝宏・鈴村健一・松来未祐）";
            agData._Mail = "zeni@joqr.net";
            agData._HashTag = "#cherrybell";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "12:00";
            agData._Repeat = true;
            agData._Name = "杉田智和のアニゲラディドゥーーン";
            agData._Mail = "gera@joqr.net";
            agData._HashTag = "#anigera";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Name = "放課後ライブ！姫イド隊";
            agData._Mail = "himeido@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "13:30";
            agData._Movie = true;
            agData._Name = " みちゃことちずるのハッピーアワー（関口未佐子・西條智鶴）";
            agData._Mail = "hhh@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "13:40";
            agData._Movie = true;
            agData._Name = "放課後ライブ！姫イド隊";
            agData._Mail = "himeido@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "14:00";
            agData._Repeat = true;
            agData._Name = "梶裕貴のひとりごと";
            agData._Mail = "kaji@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "14:30";
            agData._Repeat = true;
            agData._Name = "EMERGENCY the RADIO（NEW YOUNG・CRAZY YU・DANCING YUKARI）";
            agData._Mail = "emergency@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "15:00";
            agData._Repeat = true;
            agData._Movie = true;
            agData._Name = "逢坂市立花江学園～Radio（逢坂良太・花江夏樹）";
            agData._Mail = "ouhana@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "15:30";
            agData._Name = "内山昂輝の１クール！season2";
            agData._Mail = "one@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "16:00";
            agData._Live = true;
            agData._Movie = true;
            agData._Blog = "http://www.joqr.co.jp/blog/digista/";
            agData._Name = "A&G Girls Project（鹿野優以・石川由依・一木千洋・後藤友香里・高橋未奈美・田上真里奈・柏山奈々美・鈴木絵理・高橋花林・高宗歩未）";
            agData._Mail = "agp@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "17:00";
            agData._Name = "みなとそふとラジオ（福山綾夏）";
            agData._Mail = "minato@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "17:30";
            agData._Name = "声優グランプリ　ザ・Radio（広島編集長・田中真奈美）";
            agData._Mail = "seigura@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "18:00";
            agData._Movie = true;
            agData._Name = "桃園ひめこ・巴奎依のライトノベル学園";
            agData._Blog = @"http://www.tohogakuen.ac.jp/lightnovel/";
            agData._Mail = "light@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "18:30";
            agData._Name = "ツブ☆ドル　ユメカナラジオ！（杉田菜摘・豊田萌絵・優木かな）";
            agData._Repeat = true;
            agData._Mail = "tubu@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "19:00";
            agData._Name = "人生道でも飯田里穂";
            agData._Blog = @"http://doudemo.secondshot.jp/";
            agData._Mail = "sao@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "19:30";
            agData._Movie = true;
            agData._Name = "ステキ情報バラエティ　発信！もいとろ君（相沢舞・清都ありさ）";
            agData._Blog = @"http://seaside-c.jp/program/moitorokun/";
            agData._Mail = "moitorokun@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "20:00";
            agData._Name = "岩田光央･鈴村健一 スウィートイグニッション";
            agData._Mail = "";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "20:30";
            agData._Name = "内田";
            agData._Mail = "ikemen@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "21:00";
            agData._Live = true;
            agData._Blog = @"http://joqr.net/agson/";
            agData._Name = "A&G Tribal Radio エジソン（花江夏樹・日高里菜）";
            agData._Mail = "agson@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "23:00";
            agData._Live = true;
            agData._Blog = "http://www.comcha.net/";
            agData._Name = "A&Gメディアステーション こむちゃっとｶｳﾝﾄﾀﾞｳﾝﾌﾟﾗｽ【最大23時59分までの放送となります】（櫻井孝宏・井口裕香）";
            agData._Mail = "comcha@joqr.net";
            agData._HashTag = "#comcha";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "0:00";
            agData._Name = "戸松遥のココロ☆ハルカス";
            agData._Blog = "";
            agData._Mail = "harukas@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "0:30";
            agData._Name = "寿美菜子のラフラフ";
            agData._Mail = "375@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "1:00";
            agData._Name = "あどりぶ（巽悠衣子・大橋彩香）";
            agData._Mail = "adlib@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "1:30";
            agData._Movie = true;
            agData._Name = "大久保瑠美・原紗友里　青春学園 Girls High↑↑";
            agData._Mail = "high@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "2:00";
            agData._Name = "はりけ～んず前田と上間江望の『がむちゃら！』";
            agData._Mail = "gamucha@joqr.net";
            agData._Movie = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "2:30";
            agData._Movie = true;
            agData._Name = "れい＆ゆいの文化放送ホームランラジオ!（松嵜麗・渡部優衣）";
            agData._Mail = "hrr@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "3:00";
            agData._Name = "ラジオどっとあい　花守ゆみりのいろんなゆみりをみてゆみり";
            agData._Blog = @"http://www.joqr.co.jp/yumiri/";
            agData._Mail = "di@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Saturday;
            agData._Time = "3:30";
            agData._Name = "MAN TWO MONTH RADIO 斉藤壮馬のSOマニアック！";
            agData._Mail = "mtmr@joqr.net";
            lstAgData.Add(agData);

            // 日曜日
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "6:00";
            agData._Repeat = true;
            agData._Name = "超！A&Gスペシャル";
            agData._Mail = "sag@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "7:00";
            agData._Name = "岩田光央･鈴村健一 スウィートイグニッション";
            agData._Repeat = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "7:30";
            agData._Repeat = true;
            agData._Name = "ラジオどっとあい　花守ゆみりのいろんなゆみりをみてゆみり";
            agData._Blog = @"http://www.joqr.co.jp/yumiri/";
            agData._Mail = "di@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Repeat = true;
            agData._Time = "8:00";
            agData._Name = "戸松遥のココロ☆ハルカス";
            agData._Mail = "harukas@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Repeat = true;
            agData._Time = "8:30";
            agData._Name = "寿美菜子のラフラフ";
            agData._Mail = "375@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "9:00";
            agData._Repeat = true;
            agData._Name = "花澤香菜のひとりでできるかな";
            agData._Blog = @"http://www.joqr.co.jp/blog/hanazawa/";
            agData._Mail = "dekirukana@joqr.net";
            agData._HashTag = "#hitokana";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Repeat = true;
            agData._Time = "10:00";
            agData._Name = "高垣彩陽のあしたも晴レルヤ";
            agData._Mail = "ayahi@joqr.net";
            agData._HashTag = "#hareruya";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "10:30";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "矢作・佐倉のちょっとお時間よろしいですか（矢作紗友里・佐倉綾音）";
            agData._Blog = "";
            agData._Mail = "ojikan@joqr.net";
            agData._HashTag = "#ojikan";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "11:00";
            agData._Repeat = true;
            agData._Name = "あおいさおりの新番組（悠木碧・早見沙織）";
            agData._Mail = "doya@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "11:30";
            agData._Repeat = true;
            agData._Name = "早見沙織のふり～すたいる♪";
            agData._Mail = "frst@joqr.net";
            agData._HashTag = "#frst";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "12:00";
            agData._Repeat = true;
            agData._Name = "竹達・沼倉の初ラジ！（竹達彩奈・沼倉愛美）";
            agData._Mail = "wiwi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "12:30";
            agData._Repeat = true;
            agData._Name = "TrySailのTRYangle harmony（麻倉もも・雨宮天・夏川椎菜）";
            agData._Mail = "try@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "13:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "阿澄佳奈　星空ひなたぼっこ";
            agData._Mail = "asumin@joqr.net";
            agData._HashTag = "#hoshihina";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "14:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "井口裕香のむ～～～ん⊂（　＾ω＾）⊃";
            agData._Mail = "yukachi@joqr.net";
            agData._HashTag = "#muuuun";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "15:00";
            agData._Movie = true;
            agData._Repeat = true;
            agData._Name = "久保ユリカが１人しゃべりなんて胃が痛い。";
            agData._Mail = "shikaco@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "15:30";
            agData._Name = "洲崎西（洲崎綾・西明日香）";
            agData._Blog = "http://seaside-c.jp/program/suzakinishi/";
            agData._Repeat = true;
            agData._Mail = "suzakinishi@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "16:00";
            agData._Movie = true;
            agData._Name = "篠田みなみ・ＭＩＣあすかのクリエイターズサロン！";
            agData._Blog = "";
            agData._Mail = "mic@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "16:30";
            agData._Name = "和田昌之のWADAX Radio（和田昌之・黒岩希未代・井上奈菜）";
            agData._Blog = "";
            agData._Mail = "wadax@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "17:00";
            agData._Name = "夜中メイクが気になったから（たかはし智秋・寺川愛美・千菅春香）";
            agData._Mail = "egg@joqr.net";
            agData._Blog = "http://obc1314.com/yonaka/";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "17:30";
            agData._Name = "めっちゃすきやねん（大空直美・中島唯・松田颯水）";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "18:00";
            agData._Name = "セハガールのハードなSEGA情報RADIO「セハらじ」（井澤詩織・山岡ゆり）";
            agData._Mail = "sega@joqr.net";
            agData._Blog = @"http://www.joqr.co.jp/sega/";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "18:30";
            agData._Name = "のざP＆松永真穂のLive Dog（野崎圭一・松永真穂）";
            agData._Mail = "dog@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "19:00";
            agData._Name = "儀武ゆう子\"ＳＵＮ\"";
            agData._Movie = true;
            agData._Blog = "";
            agData._Mail = "sun@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "19:30";
            agData._Movie = true;
            agData._Name = "アフィリア・サーガの魔法学院放送部";
            agData._Mail = "afilia@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "20:00";
            agData._Name = "セガネットワークスアワー　緑川光・今井麻美・内田彩のチェンクロラジオ";
            agData._Mail = "chain@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Thursday;
            agData._Time = "20:30";
            agData._Movie = true;
            agData._Name = "瑠璃子・葵のＡＯ進化論（青木瑠璃子・葵）";
            agData._Mail = "blue@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "21:00";
            agData._Mail = "hamidase@joqr.net";
            agData._Name = "はみらじ（荒川美穂・大坪由佳・山本希望）";
            agData._Blog = "http://www.marine-e.net/sp/hami-radi/";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "21:30";
            agData._Name = "丹下桜のRadio・A・La・Mode";
            agData._Mail = "alamode@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "22:00";
            agData._Movie = true;
            agData._Mail = "gun@joqr.net";
            agData._Name = "阿部敦・植田佳奈のガンストうぇ～ぶ！";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "22:30";
            agData._Name = "諏訪部順一・西田雅一の覚醒チューン";
            agData._Mail = "kakusei@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "23:00";
            agData._Name = "梶裕貴のひとりごと";
            agData._Mail = "kaji@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "23:30";
            agData._Name = "天才軍師（安元洋貴・細谷佳正）";
            agData._Mail = "komei@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "0:00";
            agData._Name = "P.S.元気です。孝宏";
            agData._Mail = "psgenki@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "0:30";
            agData._Name = "BELOVED MEMORIES（内田雄馬・田丸篤志）";
            agData._Mail = "memoriese@joqr.net";
            agData._Blog = @"http://www.seaside-c.jp/program/belovedmemories/";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "1:00";
            agData._Name = "小野友樹のオノパラ！";
            agData._Blog = "";
            agData._Mail = "onopara@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "2:00";
            agData._Name = "生メールpresents 柿原と流田のラジオ＋（ふうちん）（柿原徹也・流田豊・永山風花）";
            agData._Mail = "knf@joqr.net";
            agData._Blog = @"http://www.joqr.co.jp/knf/";
            agData._Movie = true;
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "2:00";
            agData._Name = "セガネットワークスアワー　村川梨衣・大坪由佳のムラツボ研究所";
            agData._Mail = "muratsubo@joqr.net";
            lstAgData.Add(agData);
            agData = new AGData();
            agData._WeekDay = AGData.WeekDay.Sunday;
            agData._Time = "02:30";
            agData._Name = "セガネットワークスアワー　緑川光・今井麻美・内田彩のチェンクロラジオ";
            agData._Mail = "chain@joqr.net";
            lstAgData.Add(agData);

            FileProc.SetTimeTable(lstAgData);
        }
    }
}
