//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap e_left {
            get {
                object obj = ResourceManager.GetObject("e_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap e_right {
            get {
                object obj = ResourceManager.GetObject("e_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   http://www.agqr.jp/timetable/digital-mf.php に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LINK_TIMETABLE_MF {
            get {
                return ResourceManager.GetString("LINK_TIMETABLE_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.agqr.jp/timetable/digital-ss.php に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LINK_TIMETABLE_SS {
            get {
                return ResourceManager.GetString("LINK_TIMETABLE_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap movie {
            get {
                object obj = ResourceManager.GetObject("movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap repeat {
            get {
                object obj = ResourceManager.GetObject("repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   承認済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TWIT_STATE_FIN {
            get {
                return ResourceManager.GetString("TWIT_STATE_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未承認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TWIT_STATE_NOT {
            get {
                return ResourceManager.GetString("TWIT_STATE_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在使用中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TWIT_STATE_NOW {
            get {
                return ResourceManager.GetString("TWIT_STATE_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   金曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_FRIDAY {
            get {
                return ResourceManager.GetString("WEEK_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_MONDAY {
            get {
                return ResourceManager.GetString("WEEK_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_SATURDAY {
            get {
                return ResourceManager.GetString("WEEK_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_SUNDAY {
            get {
                return ResourceManager.GetString("WEEK_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_THURSDAY {
            get {
                return ResourceManager.GetString("WEEK_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_TUESDAY {
            get {
                return ResourceManager.GetString("WEEK_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WEEK_WEDNESDAY {
            get {
                return ResourceManager.GetString("WEEK_WEDNESDAY", resourceCulture);
            }
        }
    }
}
